### ISSUE TITLE
Unhandled error when website is down

### ISSUE THREAD

**Issue by jdeast** [rachel3834/spitzer_microlensing_tools#1]
When the website is down, the script fails:

  File "get_spitzer_mulens_targets.py", line 108, in request_target_list
    response = urllib2.urlopen(req)
[...]

  File "/h/onion0/anaconda/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error

This error should be caught and handled.

**Comment by rachel3834** [comment]
Thanks for the bug report.  I agree.  I've added some additional error handling which will catch this and exit gracefully if this occurs again.  

However, I am wondering if this would be the behaviour you'd prefer if you're using this function within your own script.  Maybe it would be better if it returned an empty target dictionary with a message?

**Comment by jdeast** [comment]
It'd be best if it could default to an older version of the table. Perhaps each time it has run it can update a local copy, and if it fails to connect, it can read that instead. That way, we can still observe if the site is down.

**Comment by rachel3834** [comment]
So the way this works is that it harvests the target list from the online targetlist page.  
If the server is down, of course there's no way to guarantee I could serve even an historical version of the targetlist.  So the best way I can think to give the code a persistent 'memory' as you describe is to provide an additional flag which, if selected, would write a copy of the targetlist to local disk whenever the online system was successfully queried.  If the web-query later fails, the code would then look for the local copy and serve that instead.  Sound reasonable?

**Comment by jdeast** [comment]
Sounds perfect.

**Comment by rachel3834** [comment]
OK.  I've re-factorized the code somewhat and provided the history functionality as described in the readme.  Documentation on how to use this option provided in the usual places.
