### ISSUE TITLE
cadence_hrs = None => error

### ISSUE THREAD

**Issue by jdeast** [rachel3834/spitzer_microlensing_tools#2]
Nate McCrady reports:

The problem is that cadence_hrs is expecting a float, but some targets in the list have this parameter as 'None' which Python then cannot cast to a float. This is line 60 of Rachel's target_class.py code.

**Comment by rachel3834** [comment]
Thanks for the detailed report, I've fixed this issue by parsing any 'None' cadence entries to zero (float).
